language: rust
rust:
  - nightly-2018-12-15
cache: cargo
install:
  - rustup component add rustfmt
  - rustup component add clippy
before_script:
  - mkdir databases
  - touch data.db
  - diesel migration run --database-url databases/data.db
script:
  - ./precommit

notifications:
  email: false
