dist: xenial
language: rust
cache: cargo

rust:
  - nightly-2019-03-12
  - nightly

matrix:
  allow_failures:
    - nightly
  fast_finish: true

install:
  - rustup component add rustfmt
  - rustup component add clippy

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - test -x $HOME/.cargo/bin/diesel || cargo install diesel_cli --no-default-features --features=postgres
  - test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook
  - test -x $HOME/.cargo/bin/mdbook-linkcheck || cargo install mdbook-linkcheck
  - diesel migration run

script:
  - ./precommit
  - mdbook build docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/book/html
  keep-history: false
  on:
    branch: master

notifications:
  email: false

services:
  - postgresql

addons:
  postgresql: '10'
