language: rust
rust:
  - nightly-2018-12-15
cache: cargo
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo build
  - cargo test
