dist: xenial
language: rust
cache: cargo

rust:
  - nightly-2019-01-26

install:
  - rustup component add rustfmt
  - rustup component add clippy

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres
  - test -x $HOME/.cargo/bin/diesel || cargo install diesel_cli --no-default-features
    --features=postgres
  - diesel migration run

script:
  - ./precommit

notifications:
  email: false

services:
  - postgresql

addons:
  postgresql: '10'
