[package]
name = "enceladus-api"
version = "0.1.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
rocket = "0.4"
serde = { version = "1.0", features = ["derive"] }
diesel = "1.4"
enceladus_macros = { path = "./macros" }

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["diesel_sqlite_pool", "json", "helmet"]

[build-dependencies]
diesel = "1.4"
diesel_migrations = "1.4"

[dev-dependencies]
serde_json = "1.0"
uuid = { version = "0.7", features = ["v4"] }
