[package]
name = "enceladus-api"
version = "0.1.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
rocket = "0.4"
serde = "1.0"
serde_derive = "1.0"
diesel = "1.3"

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["diesel_sqlite_pool", "json", "helmet"]

[build-dependencies]
diesel = "1.3"
diesel_migrations = "1.3"
