ignore = ["api/src/schema.rs"]
error_on_line_overflow = true
error_on_unformatted = true
imports_layout = "HorizontalVertical"
merge_imports = true
newline_style = "unix"
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 10
use_field_init_shorthand = true
use_try_shorthand = true
