[package]
name = "rocket_telemetry"
version = "0.1.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
parking_lot = { version = "0.9.0", features = ["nightly"] }
rocket = "0.4.2"
lazy_static = "1.3.0"
