[package]
name = "reddit"
version = "0.1.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
derive_more = "0.14.0"
itertools = "0.8.0"
lazy_static = "1.2.0"
reqwest = "0.9.10"
serde = "1.0.88"
serde_json = "1.0.38"
uuid = "0.7.2"
