[package]
name = "enceladus_macros"
version = "0.1.0"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"
syn = "0.15.26"
proc-macro2 = "0.4.27"
rand = "0.6.5"
